export const cartStyles = {
  dropdown: "absolute top-16 right-4 w-72 bg-white rounded-xl shadow-2xl border border-gray-100 z-[60] overflow-hidden",
  section: "p-4 border-b border-gray-100",
  sectionTitle: "text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3",
  itemRow: "flex justify-between items-start",
  itemContainer: "flex justify-between items-center",
  itemTitle: "text-sm font-medium text-gray-800 line-clamp-1 pr-2",
  itemPrice: "text-sm font-bold text-gray-900",
  removeBtn: "text-red-400 hover:text-red-600 ml-2",
  totalRow: "mt-4 pt-4 border-t border-gray-50 flex justify-between items-center",
  totalLabel: "text-sm font-bold text-gray-700",
  totalValue: "text-lg font-bold text-emerald-700", 
  actions: "mt-4 flex gap-2",
  clearBtn: "flex-1 py-2 text-xs font-semibold text-gray-500 hover:text-red-600 transition-colors",
  payBtn: "flex-1 bg-emerald-600 text-white py-2 rounded-lg text-xs font-bold hover:bg-emerald-700 transition-colors shadow-sm",
  emptyState: "p-8 text-center",
  emptyIcon: "w-12 h-12 text-gray-300 mx-auto mb-3",
  emptyText: "text-gray-500 font-medium text-sm",
};